### ISSUE TITLE
transmission lineages

### ISSUE THREAD

**Issue by evandiego83** [jtmccr1/fertree#3]
Hi John,

I was reading your new print on the delta variant and wondered how you got this transmission chains script to work as it seems really nice particularly as it outputs the source. I have rust installed but can't seem to get it to work. What command do you use to get fertree installed on a mac os x. 

`fertree transmission-lineages --ignore-taxa 15K_000.ancestral.txt -k location -t England -o 2021.4520547945206 -i 15K_000.combined.trees  --taxa -n > 15K_000.tl.tsv &
`

What is the 15K_000.ancestral.txt in this case and i assume the combined.trees is the beast tree file after the DTA reconstruction? 

I hope you can help.

Thank you
Evan

**Comment by jtmccr1** [comment]
Hi Evan, 
No problem from the root directory `cargo install --path .` should do the trick. I believe it will put the binary in `~/.cargo/bin` so make sure that is in your path. I plan to release precompiled binaries when I get the chance.

The help for the command should explain the options. `--ignore-taxa` is a file with taxa to skip when identifying introductions. In our case, we included travel history nodes in the DTA reconstruction but since they are tips that represent travel not samples we didn't want them included in the taxa counts of the introductions. 

Please let me know if this is helpful or if anything behaves as you don't expect. This has grown a bit organically out of an effort to make the analyses we've been running easer and the conventions I use might be a little particular. For example I allow annotations in newick strings 😬 
-JT
